---
development:
  cloud_name: muhammadyana
  api_key: '581612541965364'
  api_secret: p6SiggrMrp0aGG6Rt1n3DEqkrME
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: muhammadyana
  api_key: '581612541965364'
  api_secret: p6SiggrMrp0aGG6Rt1n3DEqkrME
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: muhammadyana
  api_key: '581612541965364'
  api_secret: p6SiggrMrp0aGG6Rt1n3DEqkrME
  enhance_image_tag: true
  static_image_support: false
